#!/usr/bin/env python3
"""Generate Doom Emacs theme (doom-michael) for both variants.

Level -> face translation per tokens.json grammar:
  level x weight x style. Underline reserved for diagnostics.
"""
import json
import os


def load():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, '..', 'ramp.json')) as fh:
        ramp = json.load(fh)
    with open(os.path.join(here, '..', 'tokens.json')) as fh:
        tokens = json.load(fh)
    return ramp, tokens

FACE_REMAP = {
    # font-lock faces -> tokens.json keys
    'font-lock-keyword-face': 'keyword',
    'font-lock-type-face': 'type',
    'font-lock-function-name-face': 'functionDef',
    'font-lock-builtin-face': 'functionCall',
    'font-lock-variable-name-face': 'variable',
    'font-lock-string-face': 'string',
    'font-lock-constant-face': 'constant',
    'font-lock-comment-face': 'comment',
    'font-lock-doc-face': 'docComment',
    'font-lock-number-face': 'number',
    'font-lock-operator-face': 'operator',
    'font-lock-preprocessor-face': 'decorator',
    'font-lock-regexp-face': 'string',
    'font-lock-negation-char-face': 'functionCall',
    'font-lock-delimiter-face': 'punctuation',
    'font-lock-bracket-face': 'punctuation',
    'font-lock-escape-face': 'stringEscape',
    'font-lock-doc-markup-face': 'docComment',
}

def props(tok, v):
    """tokens entry -> emacs face props using variant v."""
    t = v[tok['level']]['hex']
    out = []
    w = tok.get('weight')
    s = tok.get('style')
    if w == 'bold' and s == 'italic': out.append(':weight bold :slant italic')
    elif w == 'bold': out.append(':weight bold')
    elif s == 'italic': out.append(':slant italic')
    return f"'((t ({' '.join(out)} :foreground \"{t}\")))"

def emit(variant, v, tokens):
    g = lambda role: v[role]['hex']
    bg, bgAlt, sel = g('bg'), g('bgAlt'), g('selectionFill')
    ink, strong, fg, muted, faint = (g('ink'), g('strong'), g('fg'), g('muted'), g('faint'))
    L = []
    A = L.append
    A(f';;; doom-michael-{variant}.el -*- lexical-binding: t; no-byte-compile: t; -*-')
    A(f';; Generated by michael. Theme: michael {variant}. Grayscale-only, e-ink safe.')
    A(f'(deftheme doom-michael-{variant} "michael {variant} — grayscale, e-ink safe")')
    A('(custom-theme-set-faces')
    A(f" 'doom-michael-{variant}")
    A(f" '(default ((t (:background \"{bg}\" :foreground \"{fg}\"))))")
    A(f" '(cursor ((t (:background \"{ink}\"))))")
    A(f" '(region ((t (:background \"{sel}\"))))")
    A(f" '(highlight ((t (:background \"{sel}\"))))")
    A(f" '(hl-line ((t (:background \"{bgAlt}\"))))")
    A(f" '(fringe ((t (:background \"{bg}\" :foreground \"{faint}\"))))")
    A(f" '(line-number ((t (:foreground \"{faint}\"))))")
    A(f" '(line-number-current-line ((t (:foreground \"{muted}\" :weight bold))))")
    A(f" '(vertical-bar ((t (:background \"{bgAlt}\"))))")
    A(f" '(mode-line ((t (:background \"{bgAlt}\" :foreground \"{fg}\"))))")
    A(f" '(mode-line-inactive ((t (:background \"{bg}\" :foreground \"{faint}\"))))")
    A(f" '(paren-match ((t (:box (:line-width 1 :color \"{fg}\")))))")   # outline-only brace match
    A(f" '(show-paren-match ((t (:box (:line-width 1 :color \"{fg}\")))))")
    A(f" '(isearch ((t (:background \"{ink}\" :foreground \"{bg}\"))))")  # inverse = current match
    A(f" '(lazy-highlight ((t (:background unspecified :foreground \"{strong}\" :box (:line-width -1 :color \"{fg}\")))))")  # outline, not fill
    A(f" '(trailing-whitespace ((t (:background \"{bgAlt}\"))))")
    # diagnostics: underline patterns carry the kind, never color
    A(f" '(error ((t (:underline (:style line :color \"{ink}\") :weight bold))))")
    A(f" '(warning ((t (:underline (:style wave :color \"{strong}\")))))")
    A(f" '(info ((t (:underline (:style dotted :color \"{muted}\")))))")
    # font-lock from tokens.json
    for face, key in FACE_REMAP.items():
        A(f" '({face} {props(tokens['code'][key], v)})")
    A(f' (font-lock-comment-delimiter-face ((t (:slant normal :foreground "{faint}"))))')
    A(')')
    A(f'(provide-theme \'doom-michael-{variant})')
    return "\n".join(L) + "\n"

if __name__ == '__main__':
    ramp, tokens = load()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'out', 'doom-emacs')
    os.makedirs(out, exist_ok=True)
    for name in ('light', 'dark'):
        path = os.path.join(out, f'doom-michael-{name}.el')
        with open(path, 'w') as fh:
            fh.write(emit(name, ramp['variants'][name], tokens))
        print(f"wrote {path}")
