#!/usr/bin/env python3
"""Generate GNOME Terminal profile (dconf) for both variants.

Slot design for grayscale console work (bold-is-bright doubles each slot):
normal slots carry "at rest" levels; bright slots pop. Hue families that
co-occur in real console output land on DIFFERENT levels:

  git status:  modified(yellow=3 muted) vs deleted(red=1 strong) vs staged(green=2 fg)
  ls -l:       dirs(blue=4 strong, bold->12 ink) vs executables(green=2 fg bold->10 ink)
  grep match:  bold red 1 -> bright 9 ink (hard pop)
  diff:        removed(red=1) vs added(green=2)  -- distinct
  dim text:    0/8 faint (whitespace, comments in vim, progress bars)
"""
import json
import os


def load():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, '..', 'ramp.json')) as fh:
        ramp = json.load(fh)
    return ramp


# ANSI slot map: single source of truth in bench/ansi.py (also used by the
# console-session renderer, keeping generator and eval in lockstep).
import pathlib as _pl
import sys as _sys

_sys.path.insert(0, str(_pl.Path(__file__).resolve().parent.parent / 'bench'))
from ansi import SLOT_MAP as PALETTE_MAP


def palette(v):
    g = lambda role: v[role]['hex']
    return [g(normal) for normal, _ in PALETTE_MAP] + \
           [g(bright) for _, bright in PALETTE_MAP]


# Deterministic UUIDs so ProfilesList registration is idempotent.
PROFILE_UUIDS = {
    'light': '6d696368-6165-4c6c-a000-000000000001',
    'dark':  '6d696368-6165-4c6c-a000-000000000002',
}


def emit(variant_name, v):
    bg, fg = v['bg']['hex'], v['ink']['hex']
    uuid = PROFILE_UUIDS[variant_name]
    pal = palette(v)
    lines = [
        f"# michael ({variant_name}) — generated, do not edit",
        "# Usage: dconf load /org/gnome/terminal/legacy/profiles:/ < this file",
        f"[profiles:/:{uuid}]",
        f"visible-name='michael {variant_name}'",
        f"background-color='{bg}'",
        f"foreground-color='{fg}'",
        "use-theme-colors=false",
        f"cursor-background-color='{fg}'",
        f"cursor-foreground-color='{bg}'",
        "cursor-blink-mode='off'",
        "cursor-shape='ibeam'",
        "bold-is-bright=true",           # weight channel doubles as level channel
        "scrollbar-policy='never'",
        "palette=[" + ", ".join(f"'{c}'" for c in pal) + "]",
    ]
    return "\n".join(lines) + "\n"


REGISTER_SH = """\
#!/bin/sh
# Registers michael profiles with GNOME Terminal's ProfilesList (idempotent).
# Generated by michael — do not edit.
for uuid in %(uuids)s; do
    current=$(dconf read /org/gnome/terminal/legacy/profiles:/list)
    case "$current" in
        *"$uuid"*) ;;  # already registered
        *)
            if [ -z "$current" ] || [ "$current" = "@as []" ]; then
                dconf write /org/gnome/terminal/legacy/profiles:/list "['$uuid']"
            else
                dconf write /org/gnome/terminal/legacy/profiles:/list \\
                    "$(echo "$current" | sed "s/],\\s*$/,'$uuid'])/")"
            fi
            ;;
    esac
done
echo "registered: %(uuids)s"
"""


if __name__ == '__main__':
    ramp = load()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'out', 'gnome-terminal')
    os.makedirs(out, exist_ok=True)
    for name in ('light', 'dark'):
        path = os.path.join(out, f'michael-{name}.dconf')
        with open(path, 'w') as fh:
            fh.write(emit(name, ramp['variants'][name]))
        print(f"wrote {path}")
    reg = os.path.join(out, 'register.sh')
    with open(reg, 'w') as fh:
        fh.write(REGISTER_SH % {'uuids': ' '.join(PROFILE_UUIDS.values())})
    os.chmod(reg, 0o755)
    print(f"wrote {reg}")
